# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5ede23e9-d15d-4b6b-9ece-a7ffdf56fd7e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4012-BB65";
      fsType = "vfat";
    };

  fileSystems."/mnt/windows" =
    { device = "/dev/disk/by-uuid/E4E063F2E063C8FE";
      fsType = "ntfs";
    };

  fileSystems."/mnt/new_volume" =
    { device = "/dev/disk/by-uuid/260AA8A00AA86F0D";
      fsType = "ntfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a61c7646-8f89-4c37-bc45-8939f9de3016"; }
    ];

  nix.maxJobs = lib.mkDefault 12;
}
